### ISSUE TITLE
FiraSans-Bold.ttf: Internal Server Error

### ISSUE THREAD

**Issue by briatte** [danilofreire/core-econ#1]
I could be wrong, but the file at `slides/seminar-unit-2/FiraSans-Bold.ttf` is 21 bytes on my end. The contents of the file are simply: `Internal Server Error`. The problem does not show up in the next two units (haven't checked the others).

**Comment by danilofreire** [comment]
Hi briatte! Thanks for spotting that out! The file should be fixed now. I also checked 7 other files at random and they seemed okay. Ah, and sorry for the slightly clumsy zip files; it's just that they are easier to upload to [Overleaf](http://www.overleaf.com) or [ShareLaTeX](https://www.sharelatex.com). Thanks again!
